version: '3'
services:  
  db:
      image: mysql
      restart: on-failure
      container_name: joindb
      ports:
        - 3306:3306
        - 33060:33060
      volumes:
        - database_mysql:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=joindb
        - MYSQL_ROOT_PASSWORD=YgJ58cxK%m8p
      networks:
        - fullstack


volumes:
    database_mysql:

networks:
  fullstack:
    driver: bridge