version: '3'
services:
  app:
    container_name: join-app
    image: yogabagas/join-app:latest
    ports:
      - 8800:8800
    restart: on-failure
    environment:
      - APP_ENV=dev
    volumes:
      - api:/usr/src/app
    networks:
      - fullstack


volumes:
    api:

networks:
  fullstack:
    driver: bridge