version: '3'
services:
  app:
    container_name: join-app
    build: .
    working_dir: /app
    image: join-app
    ports:
      - 8800:8800
    restart: on-failure
    volumes:
      - api:/usr/src/app
    depends_on:
      - db
    networks:
      - fullstack
  
  db:
    image: mysql
    restart: on-failure
    container_name: joindb
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      - MYSQL_DATABASE=joindb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
    networks:
      - fullstack

volumes:
    api:
    database_mysql:
    cache:
      driver: local

networks:
  fullstack:
    driver: bridge